import React from 'react';
import { useLanguage } from './i18n.jsx';

const TermsModal = ({ isOpen, onClose }) => {
  const { t } = useLanguage();

  if (!isOpen) {
    return null;
  }

  return (
    <div className="fixed inset-0 z-[60] bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="w-full max-w-2xl bg-[#111111] text-[#E0E0E0] rounded-xl border border-[#2A2A2A] shadow-2xl max-h-[80vh] overflow-y-auto overscroll-contain [scrollbar-gutter:stable]">
        <div className="sticky top-0 z-10 bg-[#111111]/95 backdrop-blur-sm border-b border-[#2A2A2A] px-5 py-4 flex items-center justify-between">
          <h2 className="text-lg md:text-xl font-bold">{t('Disclaimer & Terms')}</h2>
          <button
            onClick={onClose}
            className="cursor-pointer rounded-md border border-[#3A3A3A] px-3 py-1 text-sm font-semibold hover:border-[#FFC107] hover:text-[#FFC107] transition-colors"
            aria-label={t('Close terms modal')}
          >
            ✕
          </button>
        </div>

        <div className="px-5 py-5 md:px-6 md:py-6 space-y-6 text-sm leading-relaxed">
          <section>
            <p className="font-bold text-base mb-2">{t('1. No Affiliation & Trademarks')}</p>
            <p>
              {t('IsBuyerLegit is an independent, community-driven educational tool. We are NOT affiliated with, endorsed by, or sponsored by eBay Inc., Meta Platforms, Inc. (Facebook Marketplace), OfferUp, Craigslist, PayPal, or any other third-party marketplaces or payment gateways. All product and company names are trademarks™ or registered® trademarks of their respective holders.')}
            </p>
          </section>

          <section>
            <p className="font-bold text-base mb-2">{t('2. Nature of the Service (Not Professional Advice)')}</p>
            <p>
              {t('The risk assessments (e.g., "High Risk", "Proceed with Caution") generated by this tool are estimates based on common community heuristics and user-reported fraud patterns. This tool does not perform actual background checks. The results do NOT constitute definitive financial, legal, or business advice.')}
            </p>
          </section>

          <section>
            <p className="font-bold text-base mb-2">{t('3. Limitation of Liability')}</p>
            <p>
              {t('You are solely responsible for your own shipping and business decisions. Under no circumstances shall IsBuyerLegit, its creators, or affiliates be held liable for any direct, indirect, incidental, or consequential damages. This includes, but is not limited to: financial losses from fraudulent buyers, chargebacks, lost packages, or lost profits from incorrectly flagging a legitimate buyer as high risk.')}
            </p>
          </section>

          <section>
            <p className="font-bold text-base mb-2">{t('4. Privacy & Data Handling')}</p>
            <p>
              {t("We prioritize your privacy. The information you input into this tool is used strictly for generating immediate risk assessments. We do not sell your data or your buyers' data to third-party brokers.")}
            </p>
            <p className="mt-3">
              {t('By using this site, you acknowledge that all transactions are conducted entirely at your own risk.')}
            </p>
          </section>
        </div>

        <div className="sticky bottom-0 bg-[#111111]/95 backdrop-blur-sm border-t border-[#2A2A2A] p-4 flex justify-end">
          <button
            onClick={onClose}
            className="cursor-pointer rounded-lg border-2 border-[#FFC107] px-5 py-2 text-sm font-bold text-[#FFC107] hover:bg-[#FFC107] hover:text-[#111111] transition-colors"
          >
            {t('Close')}
          </button>
        </div>
      </div>
    </div>
  );
};

export default TermsModal;